### ISSUE TITLE
Feature request: Swagger?

### ISSUE THREAD

**Issue by anderejd** [MargaretKrutikova/DeployServiceWebApi#1]
Would you be interested in an API definition using Swagger/OpenAPI? I would be interested in looking into this in that case :)

I'm primarily interested in client code generation, not for server stubs at this time.

This seems like one way, using "code first": 
 - https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio
 - https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by MargaretKrutikova** [comment]
Yes, absolutely. I was planning to look into Swagger as soon as the basic functionality is up and running. Seems like the configuration steps for setting up Swashbuckle.AspNetCore are pretty straight forward. I fix? :)

**Comment by anderejd** [comment]
Nice, pm me or post here if you would like assistance.

**Comment by MargaretKrutikova** [comment]
Swagger documentation is now available for the API. Section [swagger](https://github.com/MargaretKrutikova/deploy-script-runner-web-api#swagger) of the readme has some helpful information. Let me know if you would like to have more features in the documentation since I have fixed just the very basic swagger docs with the built-in swagger UI.
